### ISSUE TITLE
Object Storage versus Swift Object

### ISSUE THREAD

**Issue by miksch27** [IBM/watson-nao-robot#11]
Hi.
Well your notebook contains old Swift Object storage parts. Because IBM's target storage is COS/Object Storage could you update your notebook. It was an additionally learning steps ... Thanks so far ;-)   
TIA.

**Comment by RK-Sharath** [comment]
Hi, Thanks for the feedback. I have submitted a PR to include this (usage of Swift object storage) in the documentation. This code pattern uses Object Storage (Swift API).
