### ISSUE TITLE
last respond

### ISSUE THREAD

**Issue by eduardocanton** [IBM/watson-nao-robot#13]
Hello,

I´m trying to reproduce your sample and I ask a question: "What is the highest profit of Capri Italy in 2007?" I get the answer on node-red, but the robot dont say nothing. Looking in the code from Nao I dont find where  you ask to node-red for the respond.

**Comment by AlexandrLucas** [comment]
Yes, the choregraphe box for Node Red lacks any handling of the response from the Jupiter notebook. I've tried adding it myself, but I cannot figure out how to include websocket interaction to the robot.
Hope the devs will help with this.

**Comment by RK-Sharath** [comment]
@eduardocanton @Quiescitus I am checking on this and will get back soon. Apologies for the delay.

**Comment by jonesgs** [comment]
I have same issue with Pepper as @eduardocanton @Quiescitus .  I ask a question: "What is the highest profit of Capri Italy in 2007?" I get the answer on node-red, but Pepper does not say anything.  Not sure if related, but when notebook is created the only Python options are 3.4 and 3.5.  Choregraphe appears to only work with 2.7

**Comment by RK-Sharath** [comment]
@eduardocanton @Quiescitus @jonesgs It appears to be an issue with missing component in Node-RED. The fix is in process. 
@vchahalibm

**Comment by RK-Sharath** [comment]
@eduardocanton @Quiescitus @jonesgs apologies for the delay. We should have the fix soon. Thanks for your patience.

**Comment by RK-Sharath** [comment]
@eduardocanton @Quiescitus @jonesgs The issue has been fixed. Please refer to steps 5 & 6 in the documentation which will enable two way communication (question & answer). Kindly let me know if you face any issues.
