### ISSUE TITLE
Problem in Step 3

### ISSUE THREAD

**Issue by dayanalv** [IBM/watson-nao-robot#2]
Hello, 
I am writing because I can not understand how to realize this step because I create a new Workspace and the Workspace's ID of this one, I put it into the workspace.json file, but when I am going to load this file in my Watson Conversation Workspace, automatically generates a new Workspace and I don't get it why or if I'm doing something wrong.

Thank you for your time.

**Comment by RK-Sharath** [comment]
@dayanalv Please import the Workspace directly into your Watson Conversation Workspace and you are good to go. No need to update the Workspace id.
Creation of new Workspace is needed if you want to import intent, entities separately and change the existing intents and entities. 
Please let us know if you face any issues.

**Comment by RK-Sharath** [comment]
@stevemart I have edited readme to remove the step of updating Workspace id before importing it to avoid confusion.

**Comment by stevemar** [comment]
@RK-Sharath OK, please use pull requests and do not commit directly to master so we can all review the fix next time.

**Comment by RK-Sharath** [comment]
@stevemart I will use PR going forward. Thank you.
