### ISSUE TITLE
still can't run successfully

### ISSUE THREAD

**Issue by chenjgui** [IBM/watson-nao-robot#21]
Hi!
![image](https://user-images.githubusercontent.com/38098233/39126098-db9cd85e-4733-11e8-8ca9-8291d440cccc.png)
i google the wrong code "  df = df_data_*  ",but i don't find anything .
thank you very much for any help.

**Comment by stevemar** [comment]
Refer to the comment above that line. It asks for the user to rename that variable depending on what the data frame is inserted as

**Comment by chenjgui** [comment]
thank you for you help and at the end of this code,i have another mistake
i run     "start_websocket_listener()"
![image](https://user-images.githubusercontent.com/38098233/39291549-fd88322c-4965-11e8-9f9d-38611aa19ee2.png)

**Comment by chenjgui** [comment]
@stevemart 
still can't run successfully

**Comment by stevemar** [comment]
@RK-Sharath can you help out @chenjgui ? or see if you can run through this notebook

**Comment by RK-Sharath** [comment]
@stevemart the notebook works fine.
@chenjgui you need to run start websocket listener if you want to communicate with a Node-RED based URL as mentioned in the documentation. Please refer to the steps and run the Notebook.

**Comment by chenjgui** [comment]
@RK-Sharath 
Can you explain it in detail?
I still don't understand where I was wrong

**Comment by RK-Sharath** [comment]
@chenjgui Please advise whether you need to run web sockets for your requirement. What exactly are you trying to accomplish?

**Comment by RK-Sharath** [comment]
closing this issue as there's no response from the user.
